name: Vostok

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}    

    steps:
      
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      
    - name: Download Cement
      run: | 
        Invoke-WebRequest "https://github.com/skbkontur/cement/releases/download/v1.0.58/63d70a890a8a69703c066965196021afb7a793c1.zip" -Out "cement.zip"
        Expand-Archive "cement.zip" -Force -DestinationPath "./cement"       
      shell: pwsh
    
    - name: Install Cement
      run: |
        cd ./cement
        cd ./dotnet
        chmod +x ./install.sh
        ./install.sh
        ~/bin/cm --version
      shell: bash    
    
    - name: Checkout
      uses: actions/checkout@v2.0.0
        
    - name: Update deps
      run: | 
        echo $PATH
        pushd
        cd ..
        cm init
        popd
        ~/bin/cm update-deps
      shell: bash
        
    - name: Build deps
      run: ~/bin/cm build-deps
      shell: bash
    
  
