name: Vostok

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      
    - name: Download Cement
      run: Invoke-WebRequest "https://github.com/skbkontur/cement/releases/download/v1.0.58/63d70a890a8a69703c066965196021afb7a793c1.zip" -Out "cement.zip"
      shell: pwsh
    
    - name: Unpack Cement
      run: Expand-Archive "cement.zip"
      shell: pwsh
      
    - name: Install Cement
      run: cd cement/dotnet && ./install
    
  
